server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  forward-headers-strategy: framework

spring:
  profiles:
    active: @profileActive@
  application:
    name: romantic-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  sql:
    init:
      mode: always
      encoding: UTF-8
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  path: ./log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] [%X{tid}] %-20.20logger{20} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] [%X{tid}] %logger{36} - %msg%n"

romantic:
  storage:
    public-path-prefix: /uploads
    avatar-directory: avatars
    anniversary-directory: anniversaries
